### ISSUE TITLE
got an unexpected keyword argument 'img_scale'

### ISSUE THREAD

**Issue by wdings** [implus/PytorchInsight#28]
When I was running the python tools/test.py script, I encountered the following error. How can I solve it? Thanks!

$ python tools/test.py local_configs/cascade_rcnn_r50_fpn_20e.py checkpoints/cascade_rcnn_fpn_20e_old_resnet50.pth

Traceback (most recent call last):
  File "tools/test.py", line 127, in <module>
    main()
  File "tools/test.py", line 75, in main
    dataset = obj_from_dict(cfg.data.test, datasets, dict(test_mode=True))
  File "/home/wds/anaconda3/lib/python3.7/site-packages/mmcv/runner/utils.py", line 81, in obj_from_dict
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'img_scale'

**Comment by Sun-WeiZhen** [comment]
When I was running this code, I encountered the following error. How can I solve it? Thanks!
RuntimeError: Error(s) in loading state_dict for ResNet:
	Unexpected key(s) in state_dict: "epoch", "state_dict", "acc", "best_acc", "optimizer".
